GET https://api.github.com/repos/dragonstone-org/dependabot-poc/dependabot/alerts
Authorization: Bearer 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
X-GitHub-Api-Version: 2022-11-28
Accept: application/vnd.github+json

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer 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
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {
  repository(name: $name, owner: $owner) {
    name
    fullName: nameWithOwner
    description
    diskUsage
    forkCount
    stargazers(first: 5) {
        totalCount
        nodes {
            login
            name
        }
    }
    watchers {
        totalCount
    }
  }
}

{
    "name": "vscode-restclient",
    "owner": "Huachao"
}

###


https://api.github.com/graphql
Authorization: Bearer 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


###
POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer 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
X-REQUEST-TYPE: GraphQL

query {
  __type(name: "Repository") {
    name
    kind
    description
    fields {
      name
    }
  }
}

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer 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
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {  
  repository(owner: $owner, name: $name) {
    vulnerabilityAlerts(first: 20) {
      nodes {
        number
        securityVulnerability {
          advisory {
            summary
            description
            cvss {
              score
              vectorString
            }
            cwes {
              nodes {
                cweId
              }
            }
            references {
              url
            }
          }
          package {
            name
          }
          severity
        }
        createdAt
        state
        vulnerableManifestPath
        vulnerableRequirements
        id
      }
    }
    nameWithOwner
    url
  }
}

{
    "name": "ghas-alerts-from-api",
    "owner": "0gis0"
}

