@REPO_NAME = {{ $dotenv REPO_NAME }}
@OWNER = {{ $dotenv OWNER }}
@PAT = {{ $dotenv PAT }}

###

https://api.github.com/graphql
Authorization: Bearer {{ PAT }}


###
POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer {{ PAT }}
X-REQUEST-TYPE: GraphQL

query {
  __type(name: "Repository") {
    name
    kind
    description
    fields {
      name
    }
  }
}

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer {{ PAT }}
X-REQUEST-TYPE: GraphQL

query {
  __type(name: "RepositoryVulnerabilityAlertConnection") {
    name
    kind
    description
    fields {
      name
      type {
        name
        kind
        ofType {
          name
          kind
        }
      }
    }
  }
}

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer {{ PAT }}
X-REQUEST-TYPE: GraphQL

query {
  __type(name: "RepositoryVulnerabilityAlert") {
    name
    kind
    description
    fields {
      name
      type {
        name
        kind
        ofType {
          name
          kind
        }
      }
    }
  }
}

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer {{ PAT }}
X-REQUEST-TYPE: GraphQL

query {
  __type(name: "RepositoryVulnerabilityAlert") {
    name
    kind
    description
    fields {
      name
      type {
        name
        kind
        ofType {
          name
          kind
        }
      }
    }
  }
}

###

POST https://api.github.com/graphql
Content-Type: application/json
Authorization: Bearer {{ PAT }}
X-REQUEST-TYPE: GraphQL

query ($name: String!, $owner: String!) {  
  repository(owner: $owner, name: $name) {
    nameWithOwner
    url
    vulnerabilityAlerts(first: 20) {
      totalCount
      nodes {
        id
        number
        createdAt
        state
        vulnerableManifestPath
        vulnerableRequirements        
        securityVulnerability {
          package {
            name
          }
          advisory {
            severity
            summary
            description
            references{
              url
            }
            identifiers {
              type
              value
            }
            cvss {
              score     
              vectorString        
            }
            cwes(first: 5) {              
              nodes {
                cweId
                name
                description
              }
            }
          }
        }        
      }
    }
    nameWithOwner
    url
  }
}

{
    "name": "{{ REPO_NAME }}",
    "owner": "{{ OWNER }}"
}

###

# Get CodeQL alerts using GitHub CLI

https://api.github.com/repos/{{ OWNER }}/{{ REPO_NAME }}/code-scanning/alerts
Content-Type: application/json
Authorization: Bearer {{ PAT }}

###

# Get Secret Scanning alerts using GitHub CLI

https://api.github.com/repos/{{ OWNER }}/{{ REPO_NAME }}/secret-scanning/alerts
Content-Type: application/json
Authorization: Bearer {{ PAT }}