// Variables
@baseUrl = http://localhost:8080/api/v2

@token = 2126ab9137fba34eeb7cc3e48509db52fbca911d

@productName = "ghas-alerts-from-api"


###

// Create an engagement


###

// Create a test



###

POST {{baseUrl}}/findings/
Authorization: Token {{token}}
Content-Type: application/json

{
  "title": "GitHub Personal Access Token github_pat_11AA", 
  "severity": "Critical",
  "description": "GitHub Personal Access Token github_pat_11AA",
  "test": 1
}