// Variables
@baseUrl = http://localhost:8080/api/v2

@token = 2126ab9137fba34eeb7cc3e48509db52fbca911d

@productName = "ghas-alerts-from-api"
@engagementId = 17

###

# @name addTestType
POST {{baseUrl}}/test_types/
Authorization: Token {{token}}
Content-Type: application/json

{
  "name": "GitHub Advanced Security - Secret Scanning",
  "description": "GitHub Advanced Security - Secret Scanning",
  "static_tool": true,
  "active": true 
}

# @testTypeId = {{ addTestType.response.body.id }}

###

@testTypeId = 208

###

// Create a test
# @name addTest
POST {{baseUrl}}/tests/
Authorization: Token {{token}}
Content-Type: application/json

{
  "title": "GitHub Advanced Security - Secret Scanning", 
  "engagement": {{engagementId}},
  "test_type": {{testTypeId}},
  "target_start": "2025-02-20",
  "target_end": "2025-02-20"
}

###

@testId = {{ addTest.response.body.id }}

###

POST {{baseUrl}}/findings/
Authorization: Token {{token}}
Content-Type: application/json

{
  "title": "GitHub Personal Access Token github_pat_11AA", 
  "severity": "Critical",
  "description": "GitHub Personal Access Token github_pat_11AA",
  "test": {{testId}},
  "found_by": [
    {{testTypeId}}
  ],
  "active": true,
  "verified": true,
  "numerical_severity": 3
}